basePath: /api/v1/
definitions:
  requests.AccountRequest:
    properties:
      inital_balance:
        type: number
      owner:
        type: string
    type: object
  requests.TransactionRequest:
    properties:
      amount:
        type: number
      type:
        $ref: '#/definitions/utils.TransactionType'
    type: object
  requests.TransferRequest:
    properties:
      amount:
        type: number
      from_acount_id:
        type: string
      to_account_id:
        type: string
    type: object
  responses.Account:
    properties:
      balance:
        type: number
      id:
        type: string
      owner:
        type: string
    type: object
  responses.Error:
    properties:
      error:
        type: string
    type: object
  responses.Message:
    properties:
      message:
        type: string
    type: object
  responses.Transaction:
    properties:
      account_id:
        type: string
      balance:
        type: number
      id:
        type: string
      timestamp:
        type: string
      type:
        type: string
    type: object
  utils.TransactionType:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - Deposit
    - Withdrawal
    - Invalid
info:
  contact: {}
  description: RESTful API endpoints for Bank Account Management
  title: Bank Account Manager API
  version: "1.0"
paths:
  /api/v1/accounts:
    get:
      consumes:
      - application/json
      description: Retrieves all bank accounts' details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.Account'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Get all bank accounts
      tags:
      - Accounts
    post:
      consumes:
      - application/json
      description: Creates a new bank account with the provided details
      parameters:
      - description: Account details
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/requests.AccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Create a new bank account
      tags:
      - Accounts
  /api/v1/accounts/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves a bank account's details by its ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Get a bank account by ID
      tags:
      - Accounts
  /api/v1/accounts/{id}/transactions:
    get:
      consumes:
      - application/json
      description: Retrieves all transactions for the specified bank account
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.Transaction'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Get account transactions
      tags:
      - Transactions
    post:
      consumes:
      - application/json
      description: Creates a new transaction for the specified bank account
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      - description: Transaction details
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/requests.TransactionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.Transaction'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Create a new transaction
      tags:
      - Transactions
  /api/v1/transfer:
    post:
      consumes:
      - application/json
      description: Transfer funds from one account to another
      parameters:
      - description: Transfer details
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/requests.TransferRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Transfer funds between accounts
      tags:
      - Transactions
swagger: "2.0"
